# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel 
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [self-hosted, Windows]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: checkout
      uses: actions/checkout@v2
      with: 
        lfs: 'true'
    
    - name: Checkout tools repo 
      uses: actions/checkout@master
      with:
        repository: DigitalDaydreamStudios/jenkins-ue4
        path: my-tools
    
    # Runs a single command using the runners shell
    - name: Run the two time script 
      shell: powershell
      run: my-tools/build-scripts/build4-26.ps1
    
      
    #- name: Archive Windows Build
    #  uses: actions/upload-artifact@v1
    #  with:
    #    name: Fetchr.zip
    #    path: C:\actions-runner\_work\Fetchr\Fetchr\Build\Fetchr
